/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MethodologyRouteImport } from './routes/methodology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/challenge': typeof ChallengeRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/challenge': typeof ChallengeRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/challenge': typeof ChallengeRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auction' | '/challenge' | '/explore' | '/methodology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auction' | '/challenge' | '/explore' | '/methodology'
  id: '__root__' | '/' | '/auction' | '/challenge' | '/explore' | '/methodology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionRoute: typeof AuctionRoute
  ChallengeRoute: typeof ChallengeRoute
  ExploreRoute: typeof ExploreRoute
  MethodologyRoute: typeof MethodologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionRoute: AuctionRoute,
  ChallengeRoute: ChallengeRoute,
  ExploreRoute: ExploreRoute,
  MethodologyRoute: MethodologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
